name : ETL pipeline

on:
  psuh:
    branches:
      - main

jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : run python code
        uses : python extract.py

  transform-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : run python code
        uses : python transform.py

  load-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : run python code
        uses : python load.py
