# name of the pipeline

name: Pipeline

# set trigger
on:
  push:
    branches:
      - main

# set jobs
jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python program
        run: python welcome.py